apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard-external
spec:
  ports:
  - name: grafana-dashboard-external
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30600
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
