datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url:
     access: proxy
     isDefault: true
adminUser: admin
adminPassword: strongpassword
