apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-btf
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-btf
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-btf
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-btf
subjects:
- kind: ServiceAccount
  name: prometheus-btf
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-btf
  namespace: default
  labels:
    prometheus: prometheus-btf
spec:
  serviceAccountName: prometheus-btf
  serviceMonitorSelector:
    matchLabels:
      team: btf
  resources:
    requests:
      memory: 400Mi
